# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dashcam.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdashcam.proto\"\xf8\x04\n\x0bSeiMetadata\x12\x0f\n\x07version\x18\x01 \x01(\r\x12%\n\ngear_state\x18\x02 \x01(\x0e\x32\x11.SeiMetadata.Gear\x12\x14\n\x0c\x66rame_seq_no\x18\x03 \x01(\x04\x12\x19\n\x11vehicle_speed_mps\x18\x04 \x01(\x02\x12\"\n\x1a\x61\x63\x63\x65lerator_pedal_position\x18\x05 \x01(\x02\x12\x1c\n\x14steering_wheel_angle\x18\x06 \x01(\x02\x12\x17\n\x0f\x62linker_on_left\x18\x07 \x01(\x08\x12\x18\n\x10\x62linker_on_right\x18\x08 \x01(\x08\x12\x15\n\rbrake_applied\x18\t \x01(\x08\x12\x34\n\x0f\x61utopilot_state\x18\n \x01(\x0e\x32\x1b.SeiMetadata.AutopilotState\x12\x14\n\x0clatitude_deg\x18\x0b \x01(\x01\x12\x15\n\rlongitude_deg\x18\x0c \x01(\x01\x12\x13\n\x0bheading_deg\x18\r \x01(\x01\x12\"\n\x1alinear_acceleration_mps2_x\x18\x0e \x01(\x01\x12\"\n\x1alinear_acceleration_mps2_y\x18\x0f \x01(\x01\x12\"\n\x1alinear_acceleration_mps2_z\x18\x10 \x01(\x01\"I\n\x04Gear\x12\r\n\tGEAR_PARK\x10\x00\x12\x0e\n\nGEAR_DRIVE\x10\x01\x12\x10\n\x0cGEAR_REVERSE\x10\x02\x12\x10\n\x0cGEAR_NEUTRAL\x10\x03\"E\n\x0e\x41utopilotState\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0cSELF_DRIVING\x10\x01\x12\r\n\tAUTOSTEER\x10\x02\x12\x08\n\x04TACC\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashcam_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEIMETADATA._serialized_start=18
  _SEIMETADATA._serialized_end=650
  _SEIMETADATA_GEAR._serialized_start=506
  _SEIMETADATA_GEAR._serialized_end=579
  _SEIMETADATA_AUTOPILOTSTATE._serialized_start=581
  _SEIMETADATA_AUTOPILOTSTATE._serialized_end=650
# @@protoc_insertion_point(module_scope)
